name: adhd_diagnosis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.22.0
  flame_audio: ^2.10.6
  permission_handler: 11.3.1
  http: ^1.2.2
  camera: ^0.11.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/bird.png
    - assets/flappybird/audios/
    - assets/flappybird/sprites/
    - assets/game_ui/
    - assets/flappybird/icon.png
    - assets/logo.png

  fonts:
  - family: ComicFont
    fonts:
      - asset: assets/fonts/ComicFont-Regular.ttf